### ISSUE TITLE
请教个omitempty的问题

### ISSUE THREAD

**Issue by CharmingZhou** [json-iterator/go#176] opened 2017-09-19 10:20 UTC
经测试，对于结构体类型使用omitempty选项，变量声明必须以小写开头才有效，但我们导出变量又必须是大写开头，这两者相互矛盾了，不知道有没有好的解决办法

**Comment by taowen** [comment] 2017-09-19 10:55
please provide concrete example, such as the struct definition and expected json output

**Comment by CharmingZhou** [comment] 2017-09-19 11:53
package main
     
import (
    "fmt"                                                                                                                                       
    "github.com/json-iterator/go"
)

type SnsRet struct {
    Following int `json:"following"`
    Follower  int  `json:"follower"`
}       
        
type Message struct {
    Base string `json:"base,omitempty"`
    Sns  SnsRet `json:"sns,omitempty"`                                                                                                          
}       
        
func main() {
    var ret = Message{}
        
    data, err := jsoniter.Marshal(ret)
    if err != nil {
        fmt.Println(err.Error())
        return
    }   
    fmt.Println(string(data))
}       

==============================
expected:
{}
output:
{"sns":{}}

**Comment by taowen** [comment] 2017-09-19 16:17
change data, err := jsoniter.Marshal(ret) to data, err := json.Marshal(ret)

Seems like the standard lib is behaving in the same way. Not a bug, won't fix.

**Closed by taowen** 2017-09-19 16:17 UTC
